import type { Metadata } from "next";
import "./globals.scss";
import "primereact/resources/themes/mdc-dark-indigo/theme.css";
import 'primeicons/primeicons.css';
import Header from '@/app/ui/header';



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
        <html lang="en">
          <body className="antialiased">
              <header className="">
                  <Header />
              </header>

              <main className="container mx-auto max-w-screen-xl">
                  {children}
              </main>

              <footer className="container mx-auto max-w-screen-xl">

              </footer>
          </body>
        </html>
  );
}
